### PR TITLE
43 rename envs

### PR DESCRIPTION
**Pull request by DanielSprockett**
addresses issue #43:
Changes env yaml files to reflect the snakemake module, to improve modularity
also renamed sourmash.smk and sourmash.yaml to prototype_selection, to make naming more in line with other modules (i.e. reflect the output/goal instead of the tools).

### CODE REVIEW

**Review by tanaes — COMMENTED** [review]
This looks good; let's fix #42 and merge it and pull main into this branch first.

**Comment by tanaes** [comment]
Ok @DanielSprockett so now there are a few conflicts with the main branch. Now you can go ahead and open this PR branch on your local, pull upstream main, and resolve any conflicts, and then push again to your origin PR branch to fix them here.

**Comment by DanielSprockett** [comment]
ok, i think i just resolved those conflicts using the github editor.

**Comment by DanielSprockett** [comment]
random, but I changed the names of several env files, but the old ones with
old names remain on github. Can I just remove them manually, or is there
something gitty I should do instead?


-- 
*Daniel Sprockett, PhD*
Postdoctoral Associate | Moeller Lab
Department of Ecology & Evolutionary Biology
Cornell University
E451 Corson Hall
Ithaca, NY 14853

**Comment by DanielSprockett** [comment]
Also, this looks like it worked! Is that an ALL GO to start re-running the
entire pipeline on a subset of real samples on BioHPC? I think the
remaining issues all deal with the binning steps or later.


-- 
*Daniel Sprockett, PhD*
Postdoctoral Associate | Moeller Lab
Department of Ecology & Evolutionary Biology
Cornell University
E451 Corson Hall
Ithaca, NY 14853

**Pull request merged**
